services:
  webmarketapi:
    container_name: webmarketapi
    command: python3 main.py
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - mongo_bebidas
      - redis_bebidas
    stdin_open: true
    tty: true
  mongo_bebidas:
    image: mongo:7.0
    container_name: mongo
    restart: always
    volumes:
      - ./data/mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  redis_bebidas:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    command: --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis-data:/data
networks:
  default:
    name: webmarket-network
